### ISSUE TITLE
Etapas

### ISSUE THREAD

**Issue by KelvynJPereira** [dayvson009/SPE#1]
### **TODO**

1. Software

- [ ] Modelagem do sistema de gerenciamento de transmissores;
- [ ] Criação de sistema gerenciador de transmissores;
- [ ] Implementação de cominicação entre sistema de gerenciamento com equipamentos;
- [ ] Testes de funcionamento - real - do sistema com equipamentos.

2. Hardware

- [x] Compra  de equipamentos;
- [x] Testes de de comunicação com receptores e transmissores;

**Dados de testes de comunicação**

| Equipamento |  Alt. prédio |  Qtd. Paradas | Dist. Max. Alcançada  | Modificações em Equip. | Exito total | 
| ------------- | ------------- | ------------- |------------- |------------- | :---:  |
 nrf2401 | ≅65m | 20 | ≅60m |  NÃO MODIFICADO | ✅ |
 nrf2401 | ≅120m | 40 | ≅114m | NÃO MODIFICADO |❌|
 
- [ ] Estudo/Planejamento de consumo de energia dos equipamentos;
- [ ]  Formulação de banco de baterias (backups) de alimentação do sistema;
- [ ] Comunicação entre receptor e modulo de processamento de chamados;
- [ ] Comunucação entre modulo de processamento de chamados e central de gerenciamento;
- [ ] Implementação de comunicação 3G (modem) de modulo de processamento de chamados com central de gerenciamento;

4. Upgrades

- [ ] Modificações em comunicadores para melhoria do alcance;
